name: online_market
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.3.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
    
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.1
  firebase_storage: ^12.0.1

  flutter_bootstrap5: ^1.1.1+1
  get: ^4.6.6
  geolocator: ^14.0.1
  phone_form_field: ^10.0.8
  carousel_slider: ^5.1.1
  url_launcher: ^6.3.0
  flutter_map: ^8.1.1
  barcode_widget: ^2.0.4    
  image_picker: ^1.0.2
  connectivity_plus: ^6.1.0
  get_storage: ^2.1.1
  
  # New enhancements
  firebase_messaging: ^15.0.1
  firebase_analytics: ^11.0.1
  firebase_crashlytics: ^4.0.1
  shared_preferences: ^2.2.2
  speech_to_text: ^7.0.0
  flutter_local_notifications: ^19.2.1
  flutter_dotenv: ^5.1.0
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  flutter_rating_bar: ^4.0.1
  share_plus: ^11.0.0
  local_auth: ^2.1.8
  crypto: ^3.0.3
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  device_info_plus: ^11.4.0
  package_info_plus: ^8.0.0
  path_provider: ^2.1.3
  sqflite: ^2.3.3
  flutter_tts: ^4.2.3
  permission_handler: ^12.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  rename_app: ^1.4.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

flutter:

  uses-material-design: true
  
  assets:
    - assets/images/