// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqpZnvOqSQ322eVhPN7cVi01LVU-FDuBA',
    appId: '1:244538908147:android:fce79def7c4960c72e8686',
    messagingSenderId: '244538908147',
    projectId: 'alkhatib-market',
    storageBucket: 'alkhatib-market.appspot.com',
  );

  

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcCGInOImsOv8xjuUYFEDLDSej-q4JFOs',
    appId: '1:244538908147:web:c7c4e0c09d4bfcfa2e8686',
    messagingSenderId: '244538908147',
    projectId: 'alkhatib-market',
    authDomain: 'alkhatib-market.firebaseapp.com',
    storageBucket: 'alkhatib-market.appspot.com',
    measurementId: 'G-TLBSS7RE8Q',
  );

}